export default {
  iconPlus: require('../../assets/icons/icon-plus.png'),
  iconMinus: require('../../assets/icons/icon-minus.png'),
  carJazz: require('../../assets/images/jazz.jpeg'),
  carCivic: require('../../assets/images/civic.jpeg'),
  carFortuner: require('../../assets/images/fortuner.jpeg'),
  carSerena: require('../../assets/images/serena.jpeg'),
  carVoxy: require('../../assets/images/voxy.jpeg'),
  iconHome: require('../../assets/icons/home.png'),
  iconHomeA: require('../../assets/icons/home-active.png'),
  iconCart: require('../../assets/icons/cart.png'),
  iconCartA: require('../../assets/icons/cart-active.png'),
  iconProfile: require('../../assets/icons/profile.png'),
  iconProfileA: require('../../assets/icons/profile-active.png'),
  adib: require('../../assets/images/adib.jpg'),
  sicepat: require('../../assets/images/sicepat.png'),
  ralali: require('../../assets/images/ralali.png'),
  urbanhire: require('../../assets/images/urbanhire.jpeg'),
};
